### ISSUE TITLE
Error trying starting plugin?

### ISSUE THREAD

**Issue by Tankyspanky** [febalci/DomoticzPioneerAVR#1]
Hello,

I have installed the plugin, but i get a error : 

Traceback (most recent call last):
  File "plugin.py", line 15, in <module>
    import Domoticz
ImportError: No module named Domoticz

Just installed it fresh and tried to start it by hand ( im new to this all and trying to understand what im doing wrong)

thanx 

Aad

**Comment by febalci** [comment]
Actually that is not about the plugin but the error of domoticz. Try to use domoticz v 4.9700 stable and check if it gives the same error.
